Fixes & updates
t1m0thyj/WDD-scripts pull request #47
Opened 2024-04-25 18:18 UTC by dariusz-goc

Fixed for latest app version:
- ChangeWindowsAppTheme.ps1
- ChangeWindowsSystemTheme.ps1

Updated legacy script:
- ChangeLockscreenImage.ps1

2024-04-25 22:59 UTC, dariusz-goc commented
KB5036979 windows update breaks ChangeLockscreenImage.ps1, but latest update to WDD supports that function natively.

ChangeLockscreenImage.ps1 can be safely removed.

2024-04-27 13:41 UTC, t1m0thyj requested changes
@dariusz-goc Thanks for fixing these scripts!

As you mentioned the ChangeLockscreenImage script is obsolete now that WDD supports that function natively. Please remove the ChangeLockscreenImage.ps1 script and I will approve 🙂 

Also, some users have reported issues with the native lockscreen functionality in WDD, please let me know if you do as well: https://github.com/t1m0thyj/WinDynamicDesktop/issues/548

2024-04-27 16:03 UTC, dariusz-goc commented
I think I managed to remove the file. Please review again.

2024-04-27 19:37 UTC, t1m0thyj approved these changes

2024-04-27 19:39 UTC, merged